### ISSUE TITLE
resize storage account

### ISSUE THREAD

**Issue by sinev-valentine** [neonlabsorg/neon-evm#304]
The users are faced with the problem of exceeding the account storage size (2000 bytes).

Proxy should be able to increase storage size of code account.

- [ ] update neon-cli. Value "code_size" must include size of the storage used.

- [ ] update evm_loader. It is necessary to implement an instruction to increase storage size

- [ ] update proxy.  The proxy should call the instruction to increase the storage size.
